# Generated by Django 4.0.3 on 2022-07-28 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0003_alter_shoe_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='bin',
        ),
        migrations.AddField(
            model_name='shoe',
            name='shoe_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='shoes_rest.binvo'),
        ),
    ]
