# Generated by Django 4.0.3 on 2022-07-28 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0008_alter_shoe_bin_alter_shoe_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binvo',
            name='bin_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='binvo',
            name='bin_size',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='binvo',
            name='import_href',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bin', to='shoes_rest.binvo'),
        ),
    ]
